version: '3.6'
services:
  iris-database:
    build:
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    hostname: iris-database
    ports:
      - 9091:51773
      - 9092:52773

  iris-ml:
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: iris-battleship
    restart: always
    depends_on:
      - iris-database
    links:
      - iris-database
    ports:
      - 80:5000
    volumes:
      - ./data:/data
    environment:
      WAIT_HOSTS: iris-database:51773
    command: __main__.py